#!/usr/bin/env python

import yaml
import rospy
from controller import TeleopController

if __name__ == '__main__':

    controller = None
    try:
        rospy.init_node('teleop')

        params = None
        param_path = rospy.get_param('~teleop_config_path')
        with open(param_path, 'r') as f:
            params = yaml.load(f.read())
        rospy.set_param('teleop', params)

        controller = TeleopController(params)
        rate = rospy.Rate(params['drive_rate'])
        while not rospy.is_shutdown():
            controller.drive()
            rate.sleep()

    except rospy.ROSInterruptException:
        pass

    finally:
        if controller is not None:
            controller.shutdown()
